server:
  port: 80

spring:
  application:
    name: cloud-order-server
eureka:
  client:
    register-with-eureka: true  # true表示将自己注册进EurekaServer
    fetch-registry: true  # 从EurekaServer抓取已有的注册信息，单节点无所谓，集群必须设置为true才能配置ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka
