server:
  port: 8001
spring:
  application:
    name: cloud-pay-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.allst.springcloud.entities   # 所有Entity别名类所在包

eureka:
  client:
    register-with-eureka: true  # true表示将自己注册进EurekaServer
    fetch-registry: true  # 从EurekaServer抓取已有的注册信息，单节点无所谓，集群必须设置为true才能配置ribbon使用负载均衡
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eurekamaster:7001/eureka,http://eurekaslave2:7002/eureka  # eureka集群
  instance:
    instance-id: pay8001  # 主机名称的修改
    prefer-ip-address: true # 访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 30 # unit s 表示Eureka客户端向服务端发送心跳的时间间隔
    lease-expiration-duration-in-seconds: 90  # unit s 表示Eureka服务端在收到最后一次心跳等待时间上限