server:
  port: 80
spring:
  application:
    name: cloud-consulcustom-server
  # consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}