server:
  port: 9001
spring:
  application:
    name: cloud-nacos-provider-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   # 配置Nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'