server:
  port: 8006

spring:
  application:
    name: cloud-consul-server
  # consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

