server:
  port: 9527
spring:
  application:
    name: cloud-gateway-service
  cloud:  # 配置路由网关
    gateway:
      routes:
        - id: paymentRoute  # 路由的id,没有固定规则但要求唯一， 建议配合服务名
          uri: http://localhost:8001  # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**  # 断言，路径相匹配的进行路由
        - id: paymentRoute2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**
eureka:
  instance:
    hostname: gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eurekamaster:7001/eureka,http://eurekaslave2:7002/eureka  # eureka集群

