server:
  port: 9527
spring:
  application:
    name: cloud-gateway-service
  cloud:  # 配置路由网关
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能， 利用微服务名进行路由
      routes:
        - id: paymentRoute  # 路由的id,没有固定规则但要求唯一， 建议配合服务名
          # uri: http://localhost:8001  # 匹配后提供服务的路由地址
          uri: lb://cloud-pay-service
          predicates:
            - Path=/payment/get/**  # 断言，路径相匹配的进行路由
        - id: paymentRoute2
          # uri: http://localhost:8001
          uri: lb://cloud-pay-service
          predicates:
            - Path=/payment/lb/**
            - After=2020-07-28T23:19:44.383424400+08:00[Asia/Shanghai]  # 表示在该时间之后的请求才能匹配路由规则
            - Cookie=username,wayo  # 带cookie
            - Header=-X-Request-Id,\d+  # 请求头要有X-Request-Id属性并且值为整数的正在表达式
eureka:
  instance:
    hostname: gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eurekamaster:7001/eureka,http://eurekaslave2:7002/eureka  # eureka集群

